FROM python:2.7
RUN mkdir -p /app
# Set the working directory to /app

WORKDIR /app
# Copy the current directory contents into the container at /app
ADD . /app
# Install any needed packages specified in requirements.txt
#RUN pip install -r requirements.txt

