<?php
sleep(4);

session_start();
 if($_SESSION['authentication']){
    $conn=mysqli_connect('localhost','root','shivam');
    $db=mysqli_select_db($conn,'on');
    $uname=$_SESSION['u_name'];
    $pass=$_SESSION['pass'];
    
    $query="SELECT * FROM user WHERE u_name='$uname' AND pass='$pass'";
    $result=mysqli_query($conn,$query);
    $row=mysqli_fetch_array($result);
    
     
    
       if($_SERVER["REQUEST_METHOD"]=='POST'){
           if(isset($_POST['id']) && isset($_POST['p_id']) && isset($_POST['f_id'])){
                $id=mysqli_real_escape_string($conn,$_POST['id']);
                $pid=mysqli_real_escape_string($conn,$_POST['p_id']);
                $fid=mysqli_real_escape_string($conn,$_POST['f_id']);
                
                
                $sql0="SELECT * FROM project WHERE u_id='$id' AND p_id='$pid'";
                $res0=mysqli_query($conn,$sql0);
                $row0=mysqli_fetch_array($res0);
                
               
                    $sql2="SELECT * FROM files WHERE f_id='$fid' AND p_id='$pid' AND u_id='$id'";
                    $res2=mysqli_query($conn,$sql2);
                    $row2=mysqli_fetch_array($res2);
                   //use ccurl
               
                   $pn=$row0['p_name'];
                   $fn=$row2['f_name'];
               
                   // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
                   $ch = curl_init();

                   curl_setopt($ch, CURLOPT_URL, "localhost:4243/containers/create");
                   curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                   curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"Image\":\"$pn\",\"Cmd\": [\"python\",\"$fn\"]}");
                   curl_setopt($ch, CURLOPT_POST, 1);

                   $headers = array();
                   $headers[] = "Content-Type: application/json";
                   curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

                   $result = curl_exec($ch);
                   if (curl_errno($ch)) {
                       echo 'Error:' . curl_error($ch);
                   }
                   curl_close ($ch);
 
                   $result=json_decode($result,true);
                   
                   //get two element Id and Warnings
                   //echo $result['Warnings'].'<br>'.$result['Id'].'<br>';
                   
                   if($result['Warnings'] == null){
                        //start container using curl
                        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
                        $ch = curl_init();
                        $cont_id=$result['Id']; //container id
                        curl_setopt($ch, CURLOPT_URL, "localhost:4243/containers/$cont_id/start");
                        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                        curl_setopt($ch, CURLOPT_POST, 1);

                        $result = curl_exec($ch);
                        if (curl_errno($ch)) {
                            echo 'Error:' . curl_error($ch);
                        }
                        curl_close ($ch);
                        //fetch the result
                        //fetch logs
                        $ch = curl_init();

                        curl_setopt($ch, CURLOPT_URL, "localhost:4243/containers/$cont_id/logs?stdout=1");
                        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

                        $result = curl_exec($ch);
                           if (curl_errno($ch)) {
                                echo 'Error:' . curl_error($ch);
                           }
                        curl_close ($ch);
                        
                        if($result == null){
                           echo 'no result';
                        }
                        else{
                           echo '<pre style="white-space:pre-wrap;white-space: -moz-pre-wrap; white-space: -pre-wrap; white-space: -o-pre-wrap; word-wrap: break-word; word-wrap: break-all;">'.
                           $result
                           .'</pre>';
                        } 
                   }
                   else{
                     //error
                     echo 'you are here';
                   }
                   
           }
           else{
            
           }
       }
    
    
    
 }
 else{
    
 }
?>